// root/p-vue/src/components/lists/Cocktail.vue
<template>
	<article v-if="cocktail" class="app-article">
		<section class="app-article__block">
			<h2 class="app-article__block--title">{{ cocktail.strDrink }}</h2>
			<p><strong>Category:</strong> {{ cocktail.strCategory }}</p>
			<p><strong>Alcoholic:</strong> {{ cocktail.strAlcoholic }}</p>
			<p><strong>Glass:</strong> {{ cocktail.strGlass }}</p>
			<p><strong>Instructions:</strong> {{ cocktail.strInstructions }}</p>
			<h3 class="app-article__block--subtitle">Ingredients</h3>
			<ul>
				<li v-for="(v, index) in ingredients" :key="`${index}_image`">
					{{ v.name }} {{ v.measure }}
				</li>
			</ul>
		</section>
		<Image :image="cocktail.strDrinkThumb" :alt="cocktail.strDrink" />
	</article>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { CocktailDetails } from '@/types/CocktailDetails';
import { extractIngredients } from '@/utils/extractIngredients';
import Image from '~/components/elements/Image.vue';

const { cocktail } = defineProps<{ cocktail: CocktailDetails }>();

const ingredients = computed(() => extractIngredients(cocktail));
</script>

// root/p-angular/src/app/components/lists/cocktail/cocktail.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { NgForOf, NgClass, NgIf } from '@angular/common';
import { ImageComponent } from '~/components/elements/image/image.component';
import { extractIngredients } from '@/utils/extractIngredients';
import { CocktailDetails } from '@/types/CocktailDetails';

@Component({
	selector: 'app-cocktail',
	standalone: true,
	imports: [NgForOf, NgClass, NgIf, ImageComponent],
	templateUrl: './cocktail.component.html'
})
export class CocktailComponent implements OnChanges {
	@Input() cocktail: CocktailDetails | null = null;
	ingredients: { name: string, measure: string }[] | null = null;

	ngOnChanges(changes: SimpleChanges): void {
		if (changes['cocktail'] && this.cocktail) {
			this.ingredients = extractIngredients(this.cocktail);
		}
	}
}
<article *ngIf="cocktail" class="app-article app-main__drinks--coctail">
	<section class="app-article__block">
		<h2 class="app-article__block--title">{{ cocktail.strDrink }}</h2>
		<p><strong>Category:</strong> {{ cocktail.strCategory }}</p>
		<p><strong>Alcoholic:</strong> {{ cocktail.strAlcoholic }}</p>
		<p><strong>Glass:</strong> {{ cocktail.strGlass }}</p>
		<p><strong>Instructions:</strong> {{ cocktail.strInstructions }}</p>
		<h3 class="app-article__block--subtitle">Ingredients</h3>
		<ul>
			<li *ngFor="let ingredient of ingredients">
				{{ ingredient.name }} {{ ingredient.measure }}
			</li>
		</ul>
	</section>
	<app-image [src]="cocktail.strDrinkThumb" [alt]="cocktail.strDrink"></app-image>
</article>
