// root/p-angular/src/app/components/blocks/aside/aside.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { NgForOf, NgClass } from '@angular/common';
import { RouterModule } from '@angular/router';
import { cocktails } from '@/data/cocktails';

interface Cocktail {
	code: string;
	name: string;
}

@Component({
	selector: 'app-aside',
	standalone: true,
	imports: [NgForOf, NgClass, RouterModule],
	templateUrl: './aside.component.html'
})
export class AppAsideComponent {
	cocktails: Cocktail[] = cocktails;

	constructor(public router: Router, private route: ActivatedRoute) {

		console.log(this.cocktails);
	}

	isActive(cocktailCode: string): boolean {
		return this.route.snapshot.firstChild?.routeConfig?.path === cocktailCode;
	}
}

<aside class="app-aside">
	<nav class="app-aside__nav">
		<a *ngFor="let cocktail of cocktails"
			[routerLink]="['/', cocktail.code]"
			class="app-aside__nav--link"
			[ngClass]="{ 'active': isActive(cocktail.code) }">
			{{ cocktail.name }}
		</a>
	</nav>
</aside>

// root/p-vue/src/components/blocks/Aside.vue
<template>
	<aside class="app-aside">
		<nav class="app-aside__nav">
			<router-link
				v-for="cocktail in cocktails"
				:key="cocktail.code"
				:to="`/${cocktail.code}`"
				class="app-aside__nav--link"
				:class="{ 'active': route.name === cocktail.code }
			">
				{{ cocktail.name }}
			</router-link>
		</nav>
	</aside>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { cocktails } from '@/data/cocktails';

const route = useRoute();

const isActiveRoute = (code: string) => {
	return computed(() => route.name === code);
};
</script>
