// root/p-react/src/components/blocks/Aside.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { Cocktail } from '@/types/Cocktail';
import { cocktails } from '@/data/cocktails';

const Aside: React.FC = () => {
	return (
		<aside className="app-aside">
			<nav className="app-aside__nav">
				{cocktails.map((cocktail: Cocktail) => (
					<NavLink
						key={cocktail.code}
						to={`/${cocktail.code}`}
						className={({ isActive }) => (isActive ? 'active' : '') + ' app-aside__nav--link'}
					>
						{cocktail.name}
					</NavLink>
				))}
			</nav>
		</aside>
	);
};

export default Aside;

// root/p-vue/src/components/blocks/Aside.vue
<template>
	<aside class="app-aside">
		<nav class="app-aside__nav">
			<router-link
				v-for="cocktail in cocktails"
				:key="cocktail.code"
				:to="`/${cocktail.code}`"
				class="app-aside__nav--link"
				:class="{ 'active': route.name === cocktail.code }
			">
				{{ cocktail.name }}
			</router-link>
		</nav>
	</aside>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { cocktails } from '@/data/cocktails';

const route = useRoute();

const isActiveRoute = (code: string) => {
	return computed(() => route.name === code);
};
</script>
