// root/p-vue/src/App.vue
<template>
	<div class="app-container">
		<Aside />
		<router-view />
		<div v-if="isLoading">Loading...</div>
		<div v-else-if="error">Error: {{ error }}</div>
	</div>
	<div class="app-footer app-container">
		<span>© 2024</span>
		<span>ss-web</span>
	</div>
</template>

<script lang="ts" setup>
import { onMounted, computed } from 'vue';
import { useCocktailStore } from '~/store';
import { cocktailCodes } from '@/data/cocktails';
import debounce from '@/utils/debounce';
import Aside from './components/blocks/Aside.vue';

const cocktailStore = useCocktailStore();
const isLoading = computed(() => cocktailStore.isLoading);
const error = computed(() => cocktailStore.error);

onMounted(async () => {
	for (const code of cocktailCodes) {
		await new Promise<void>((resolve) => {
			const delayedFetch = debounce(async () => {
				await cocktailStore.fetchCocktails(code);
				resolve();
			}, 50);
			delayedFetch();
		});
	}
});
</script>

// root/p-react/src/App.tsx
import React, { useEffect, useRef } from 'react';
import { BrowserRouter as Router, Routes, Navigate, Route } from 'react-router-dom';
import { cocktailCodes } from '@/data/cocktails';
import cocktailStore from '~/store';
import Drinks from '~/components/pages/Drinks';
import NotFound from '~/components/pages/NotFound';
import Aside from '~/components/blocks/Aside';
import debounce from '@/utils/debounce';

const App: React.FC = () => {
	const isFirstLoad = useRef(true); // load only one time

	useEffect(() => {
		if (isFirstLoad.current) {
			isFirstLoad.current = false;
			const fetchAllDrinks = async () => {
				for (const code of cocktailCodes) {
					await new Promise<void>((resolve) => {
						const delayedFetch = debounce(async () => {
							await cocktailStore.fetchCocktails(code);
							resolve();
						}, 50);
						delayedFetch();
					});
				}
			};
			fetchAllDrinks();
		}
	}, []);

	if (cocktailStore.isLoading) {
		return <div>Loading...</div>;
	}

	if (cocktailStore.error) {
		return <div>Error: {cocktailStore.error}</div>;
	}

	return (
		<Router>
			<div className="app-container">
				<Aside />
				{cocktailStore.isLoading}
				<Routes>
					<Route path="/" element={<Navigate to="/margarita" />} />
					<Route path="/margarita" element={<Drinks />} />
					<Route path="/a1" element={<Drinks />} />
					<Route path="/mojito" element={<Drinks />} />
					<Route path="/kir" element={<Drinks />} />
					<Route path="*" element={<NotFound />} />
				</Routes>
			</div>
			<div className="app-footer app-container">
				<span>© 2024</span>
				<span>ss-web</span>
			</div>
		</Router>
	);
};

export default App;
