// root/p-vue/src/components/pages/Drinks.vue
<template>
	<main class="app-main">
		<header class="app-main__header">
			<h1 class="app-main__header--title">Drinks (vue)</h1>
		</header>
		<section class="app-main__drinks">
			<Cocktail v-for="drink in drinks" :key="drink.idDrink" :cocktail="drink" class="app-main__drinks--coctail" />
		</section>
	</main>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import { useCocktailStore } from '~/store';
import Cocktail from '~/components/lists/Cocktail.vue';

const route = useRoute();
const cocktailStore = useCocktailStore();

const drinks = computed(() => (cocktailStore.cocktails[route.name as string] || []));
</script>

// root/p-react/src/components/pages/Drinks.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import { useLocation } from 'react-router-dom';
import { CocktailDetails } from '@/types/CocktailDetails';
import Cocktail from '~/components/lists/Cocktail';
import cocktailStore from '~/store';

const Drinks: React.FC = observer(() => {
	const location = useLocation();
	const path = location.pathname.substring(1); // remove first slash

	const drinks = cocktailStore.cocktails[path] || [];

	return (
		<main className="app-main">
			<header className="app-main__header">
				<h1 className="app-main__header--title">Drinks (react)</h1>
			</header>
			<section className="app-main__drinks">
				{drinks.map((drink: CocktailDetails) => (
					<Cocktail cocktail={drink} key={drink.idDrink} />
				))}
			</section>
		</main>
	);
});

export default Drinks;
