// root/p-react/src/components/elements/Image.tsx
import React from 'react';
import { ImageProps } from '@/types/ImageProps';
import { LazyLoadImage } from "react-lazy-load-image-component";

const Image: React.FC<ImageProps> = ({ image, alt }) => (
	<LazyLoadImage src={image}
		width={200} height={200}
		alt={alt}
		className="app-image"
	/>
);

export default Image;

// root/p-vue/src/components/elements/Image.vue
<template>
	<img v-lazy="lazyOptions" :alt="alt" class="app-image" />
</template>

<script setup lang="ts">
import Error from '@/assets/images/error.svg';
import Loading from '@/assets/images/loading.svg';

const { image, alt } = defineProps(['image', 'alt']);
const lazyOptions = { src: image, loading: Loading, error: Error };
</script>
